Automated updates

diff --git a/test b/test
--- a/test
+++ b/test
@@ -3,6 +3,22 @@
 set -Eeuo pipefail
 exitcode=0
 
+    printf "13-beta2-postgis-3.0.1: "
+    output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm nickblah/postgis:13-beta2-postgis-3.0.1 2>&1 || true)
+    if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
+      exitcode=1
+      echo "Error"
+      echo "$output"
+      echo
+    elif [[ "$output" =~ "PostGIS Tests: OK" ]]; then
+      echo "OK"
+    else
+      exitcode=1
+      echo "Unexpected Error"
+      echo "$output"
+      echo
+    fi
+
     printf "12.3-postgis-3.0.1: "
     output=$(docker run -v $(pwd)/test.sh:/docker-entrypoint-initdb.d/test.sh -e POSTGRES_PASSWORD=password --rm nickblah/postgis:12.3-postgis-3.0.1 2>&1 || true)
     if [[ "$output" =~ "PostGIS Tests: Error" ]]; then
